apiVersion: v1
kind: ConfigMap
metadata:
  name: backup-api-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/backupdb
  SPRING_DATASOURCE_USERNAME: postgres
  STORAGE_EMULATOR_HOST: http://fake-gcs-service:4443
